services:
  web:
    build:
      dockerfile: Dockerfile
      tags:
        - lytathi/sportclub
    environment:
      FLASK_DEBUG: true
    ports:
      - 5000:5000
#    links:
#      - db
#
#  db:
#    image: mysql
#    restart: always
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d/:ro
#    environment:
#      MYSQL_ROOT_PASSWORD: root1234
#    ports:
#      - 3306:3306
